layer_fields = [
    {"name": "OBJECTID","type": "esriFieldTypeOID", "alias": "OBJECTID", "sqlType": "sqlTypeOther","nullable": False,"editable": False,  "domain": None, "defaultValue": None},
    {"name": "id", "type": "esriFieldTypeInteger", "alias": "ID"},
    {"name": "fullname", "type": "esriFieldTypeString", "alias": "Full Name", "length": 100},
    {"name": "customerid", "type": "esriFieldTypeInteger", "alias": "Customer ID"},
    {"name": "phone_number", "type": "esriFieldTypeDouble", "alias": "Phone Number"},
    {"name": "emaill_address", "type": "esriFieldTypeString", "alias": "Email Address", "length": 100},
    {"name": "location", "type": "esriFieldTypeString", "alias": "Location", "length": 150},
    {"name": "feeder_name", "type": "esriFieldTypeString", "alias": "Feeder Name", "length": 100},
    {"name": "vendor_id", "type": "esriFieldTypeString", "alias": "Vendor ID", "length": 50},
    {"name": "dt", "type": "esriFieldTypeInteger", "alias": "DT"},
    {"name": "meter_number", "type": "esriFieldTypeDouble", "alias": "Meter Number"},
    {"name": "meter_phase", "type": "esriFieldTypeString", "alias": "Meter Phase", "length": 20},
    {"name": "disco", "type": "esriFieldTypeString", "alias": "Disco", "length": 50},
    {"name": "state", "type": "esriFieldTypeString", "alias": "State", "length": 50},
    {"name": "installation_status", "type": "esriFieldTypeString", "alias": "Installation Status", "length": 50},
    {"name": "Installer_number", "type": "esriFieldTypeString", "alias": "Installer Number", "length": 50},
    {"name": "installer", "type": "esriFieldTypeString", "alias": "Installer", "length": 100},
    {"name": "date_assigned", "type": "esriFieldTypeDate", "alias": "Date Assigned"},
    {"name": "install_date", "type": "esriFieldTypeDate", "alias": "Install Date"},
    {"name": "installer_remark", "type": "esriFieldTypeString", "alias": "Installer Remark", "length": 255},
    {"name": "customer_remark", "type": "esriFieldTypeString", "alias": "Customer Remark", "length": 255},
    {"name": "disco_seal", "type": "esriFieldTypeString", "alias": "Disco Seal", "length": 50},
    {"name": "nemsa_seal", "type": "esriFieldTypeDouble", "alias": "NEMSA Seal"},
    {"name": "customer_date", "type": "esriFieldTypeDate", "alias": "Customer Date"},
    {"name": "commissioned", "type": "esriFieldTypeSmallInteger", "alias": "Commissioned"},
    {"name": "date_commissioned", "type": "esriFieldTypeDate", "alias": "Date Commissioned"},
    {"name": "date_disco", "type": "esriFieldTypeDate", "alias": "Date Disco"},
    {"name": "expected_date", "type": "esriFieldTypeDate", "alias": "Expected Date"},
    {"name": "disco_remark", "type": "esriFieldTypeString", "alias": "Disco Remark", "length": 255},
    {"name": "supervisor", "type": "esriFieldTypeString", "alias": "Supervisor", "length": 100},
    {"name": "latitude", "type": "esriFieldTypeDouble", "alias": "Latitude"},
    {"name": "longitude", "type": "esriFieldTypeDouble", "alias": "Longitude"},
    {"name": "d_latitude", "type": "esriFieldTypeDouble", "alias": "Decimal Latitude"},
    {"name": "d_longitude", "type": "esriFieldTypeDouble", "alias": "Decimal Longitude"},
    {"name": "installer_accept_status", "type": "esriFieldTypeSmallInteger", "alias": "Installer Accept Status"},
    {"name": "date_installer_accepted", "type": "esriFieldTypeDate", "alias": "Date Installer Accepted"},
    {"name": "date_installer_assigned", "type": "esriFieldTypeDate", "alias": "Date Installer Assigned"},
    {"name": "address", "type": "esriFieldTypeString", "alias": "Address", "length": 255},
    {"name": "lga", "type": "esriFieldTypeString", "alias": "LGA", "length": 100},
    {"name": "installer_sealnumber", "type": "esriFieldTypeString", "alias": "Installer Seal Number", "length": 50},
    {"name": "installationid", "type": "esriFieldTypeString", "alias": "Installation ID", "length": 50},
    {"name": "installationstatus", "type": "esriFieldTypeSmallInteger", "alias": "Installation Status Boolean"},
    {"name": "schedule_id", "type": "esriFieldTypeInteger", "alias": "Schedule ID"},
    {"name": "scheduledate", "type": "esriFieldTypeDate", "alias": "Schedule Date"},
    {"name": "contract_id", "type": "esriFieldTypeString", "alias": "Contract ID", "length": 50},
    {"name": "meterengineer", "type": "esriFieldTypeString", "alias": "Meter Engineer", "length": 100},
    {"name": "csp", "type": "esriFieldTypeString", "alias": "CSP", "length": 100},
    {"name": "region", "type": "esriFieldTypeString", "alias": "Region", "length": 100},
    {"name": "tsp", "type": "esriFieldTypeString", "alias": "TSP", "length": 100},
    {"name": "installationstarts", "type": "esriFieldTypeSmallInteger", "alias": "Installation Starts"},
    {"name": "installationstarts_date", "type": "esriFieldTypeDate", "alias": "Installation Starts Date"},
    {"name": "installerarrived", "type": "esriFieldTypeSmallInteger", "alias": "Installer Arrived"},
    {"name": "installerarrived_date", "type": "esriFieldTypeDate", "alias": "Installer Arrived Date"},
    {"name": "prop_scheme", "type": "esriFieldTypeString", "alias": "PROP Scheme", "length": 100}
]
